# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  Major: '1'
  Minor: '2'
  Patch: '0'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore' # Options: restore, pack, push, custom
    restoreSolution: 'src/*.sln' # Required when command == Restore
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'

- task: MSBuild@1
  inputs:
    solution: 'src/*.sln' 
    configuration: 'Release'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: '**/*.nuspec'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: nuget.org

